### PR TITLE
React-Redux Project - Space Hub - Final Step

### PR DESCRIPTION
**Pull request by jmontanholi**
## In this project my partner and I implemented the following:
[Video explanation of project](https://www.loom.com/share/122ae77b47b3453797d7a9772346b447)
* ### A Space related website
   * #### Rockets Page
       * ##### Rockets images
       * ##### Rockets names
       * ##### Rockets descriptions
       * ##### Button to reserve rockets 
   * #### Missions Page
       * ##### Missions names
       * ##### Missions descriptions
       * ##### Button to join missions
   * #### Profile Page
       * ##### Reserved rockets names
       * ##### Joined missions names
       * ##### Buttons to cancel rocket reservation or sign off missions

### CODE REVIEW

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
# Hi @jmontanholi and @ArthurGC👏,

Amazing job guys!! you nailed this.. I can see the hard work from your project However, there is a small issue that you still need to work on to go to the next project but you are almost there! my major highlights for your projects are:

- PR is professional
- Commits messages are many and descriptive this shows that you were dedicated
- Followed git workflows
- Well demonstrated your project is the video


## Required Changes ♻️
- [ ] you should write unit tests with React Testing Library and Jest 
- [ ] Remember to add how to run tests in your README



### Cheers and Keep Rocking!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jmontanholi** [comment]
Hello @DeliceLydia!

Thanks for the feedback, unfortunately, I can't find anywhere saying that we should do tests for this project. It is not in the kanban board we had to copy nor in the project requirements for it, could you please show me?

**Comment by DeliceLydia** [comment]
## Hello @jmontanholi 
test

my guidelines said so!

I am sorry for the inconvenience

**Review by arslanbisharat — APPROVED** [review]
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashbaord. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Comment by jmontanholi** [comment]
I'm sorry. I am a bit confused now, should I do the tests or not?

**Comment by DeliceLydia** [comment]
Hello @jmontanholi,

 I am sorry for what just happened.. There might be a server problem
we claimed your PR as 2 reviewers so you can see the 2nd one approved it I too am still confused
about what happened but meanwhile check if your dashboard changed status then you move on! If not you will
let me know!

Regards,

Lydia

**Comment by jmontanholi** [comment]
The button changed to submit instead of changes requested. Thanks for the answer. Sorry!

**Comment by DeliceLydia** [comment]
Okey then your project is approved you can merge and go to the next project!

**Pull request merged**
